apiVersion: v1
kind: Service
metadata:
  name: pg-postgresql-clusterip
  namespace: infra
spec:
  selector:
    app: pg
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
